package com.utils;

public interface Constants {

    //成本中心
    String COST_CENTRE_ORDER = "5007010200";
    String COST_CENTRE_SELF_TO_DIS = "null";
    String COST_CENTRE_DIS_TO_SELF = "5007010200";
    String COST_CENTRE_RE_SKU = "5050080101";
    String COST_CENTRE_RE_GIFT = "5050080101";
    String COST_CENTRE_SUNING = "170000131";
    String COST_CENTRE_XINLANG = "170000125";
    //
    String JING_DONG_NEED_OUTSTORAGE = "360_Waitting";
    String JING_DONG_NEED_SENDING = "360_OutStorage";
    //Sync Task UUID
    double MAX_DOUBLE_VALUE = 99999999999999.0;

    String SYNC_ID_SALES_ORDER_NOPAY = "SYNCUUID_SYNCUUID_SYNCUUID_00001";
    String SYNC_ID_SALES_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00002";
    String SYNC_ID_SALES_ORDER_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00003";
    String SYNC_ID_SALES_ORDER_SEND = "SYNCUUID_SYNCUUID_SYNCUUID_00004";
    String SYNC_ID_SALES_ORDER_FINISH = "SYNCUUID_SYNCUUID_SYNCUUID_00005";
    String SYNC_ID_REFUND_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00006";
    String SYNC_ID_ALIPAY = "SYNCUUID_SYNCUUID_SYNCUUID_00007";

    String SYNC_ID_360BUY_SX_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00050";
    String SYNC_ID_360BUY_SX_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00051";
    String SYNC_ID_360BUY_SX_REFUND = "SYNCUUID_SYNCUUID_SYNCUUID_00052";

    String SYNC_ID_360BUY_QS_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00053";
    String SYNC_ID_360BUY_QS_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00054";
    String SYNC_ID_360BUY_QS_REFUND = "SYNCUUID_SYNCUUID_SYNCUUID_00055";

    String SYNC_ID_360BUY_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00008";
    String SYNC_ID_360BUY_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00009";
    String SYNC_ID_360BUY_REFUND = "SYNCUUID_SYNCUUID_SYNCUUID_00010";

    String SYNC_ID_CREATE_SAP_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00011";
    String SYNC_ID_UPLOAD_SAP_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00012";
    String SYNC_ID_GET_INVOICE_CODE = "SYNCUUID_SYNCUUID_SYNCUUID_00013";
    String SYNC_ID_SEND_SMS = "SYNCUUID_SYNCUUID_SYNCUUID_00014";
    String SYNC_ID_SEND_MAIL = "SYNCUUID_SYNCUUID_SYNCUUID_00015";
    String SYNC_ID_GET_TRADERATES = "SYNCUUID_SYNCUUID_SYNCUUID_00016";
    String SYNC_AMAZON_UNSHIPED = "SYNCUUID_SYNCUUID_SYNCUUID_00017";
    String SYNC_ANAZON_SHIPED = "SYNCUUID_SYNCUUID_SYNCUUID_00018";
    String SYNC_ID_NIP_ORDER_NOPAY = "SYNCUUID_SYNCUUID_SYNCUUID_00021";
    String SYNC_ID_NIP_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00022";
    String SYNC_ID_NIP_ORDER_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00023";
    String SYNC_ID_NIP_ORDER_SEND = "SYNCUUID_SYNCUUID_SYNCUUID_00024";
    String SYNC_ID_NIP_ORDER_FINISH = "SYNCUUID_SYNCUUID_SYNCUUID_00025";

    String SYNC_ID_SUNING_ORDER_NOPAY = "SYNCUUID_SYNCUUID_SYNCUUID_00031";
    String SYNC_ID_SUNING_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00032";
    String SYNC_ID_SUNING_ORDER_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00033";
    String SYNC_ID_SUNING_ORDER_SEND = "SYNCUUID_SYNCUUID_SYNCUUID_00034";
    String SYNC_ID_SUNING_ORDER_FINISH = "SYNCUUID_SYNCUUID_SYNCUUID_00035";
    String SYNC_ID_SUNING_REFUND_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00036";

    String SYNC_ID_360BUY2_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00037";
    String SYNC_ID_360BUY2_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00038";
    String SYNC_ID_360BUY2_REFUND = "SYNCUUID_SYNCUUID_SYNCUUID_00039";

    //天猫辅料
    String SYNC_ID_SALES_ORDER_NOPAY_ACC = "SYNCUUID_SYNCUUID_SYNCUUID_00040";
    String SYNC_ID_SALES_ORDER_ACC = "SYNCUUID_SYNCUUID_SYNCUUID_00041";
    String SYNC_ID_SALES_ORDER_CLOSE_ACC = "SYNCUUID_SYNCUUID_SYNCUUID_00042";
    String SYNC_ID_SALES_ORDER_SEND_ACC = "SYNCUUID_SYNCUUID_SYNCUUID_00043";
    String SYNC_ID_SALES_ORDER_FINISH_ACC = "SYNCUUID_SYNCUUID_SYNCUUID_00044";
    String SYNC_ID_REFUND_ORDER_ACC = "SYNCUUID_SYNCUUID_SYNCUUID_00045";

    //立邦探致
    String SYNC_ID_360BUY_TS_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00056";
    String SYNC_ID_360BUY_TS_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00057";

    //立邦诚泛专卖店
    String SYNC_ID_360BUY_CF_ORDER = "SYNCUUID_SYNCUUID_SYNCUUID_00058";
    String SYNC_ID_360BUY_CF_CLOSE = "SYNCUUID_SYNCUUID_SYNCUUID_00059";

    //TaoBaoPBSync
    String SYNC_ID_SALES_ORDER_NOPAY_PB = "SYNCUUID_SYNCUUID_SYNCUUID_00060";
    String SYNC_ID_SALES_ORDER_PB = "SYNCUUID_SYNCUUID_SYNCUUID_00061";
    String SYNC_ID_SALES_ORDER_CLOSE_PB = "SYNCUUID_SYNCUUID_SYNCUUID_00062";
    String SYNC_ID_SALES_ORDER_SEND_PB = "SYNCUUID_SYNCUUID_SYNCUUID_00063";
    String SYNC_ID_SALES_ORDER_FINISH_PB = "SYNCUUID_SYNCUUID_SYNCUUID_00064";
    String SYNC_ID_REFUND_ORDER_PB = "SYNCUUID_SYNCUUID_SYNCUUID_00065";

    //O2O订单推送到CRM
    String SYNC_ID_SEND_O2O_ORDER_TO_CRM = "SYNCUUID_SYNCUUID_SYNCUUID_00100";
    //iColor订单同步
    String SYNC_ID_SALES_ORDER_ICOLOR = "SYNCUUID_SYNCUUID_SYNCUUID_00200";
    String SYNC_ID_SALES_ORDER_CLOSE_ICOLOR = "SYNCUUID_SYNCUUID_SYNCUUID_00201";
    String SYNC_ID_SALES_ORDER_REFUND_ICOLOR = "SYNCUUID_SYNCUUID_SYNCUUID_00202";


    //补打款状态
    int RE_PAY_STATUS_APPLY = 1;
    int RE_PAY_STATUS_PAY = 2;

    int STATUS_NO = -99;

    String SO_CODE = "SalesOrder_code";
    String SO_FULLADDRESS = "SalesOrder_fullAddress";
    String SO_SELF_WH_ORGID = "SalesOrder_orgId";
    String SO_STATE = "SalesOrder_state";
    String SO_CITY = "SalesOrder_city";
    String SO_COUNTY = "SalesOrder_county";
    String SOLN_SUM_PRICE = "SalesOrderLine_SumPrice";
    String SO_SUM_PRICE = "SalesOrder_SumPrice";
    String RF_SUM_PRICE = "RefundOrder_SumPrice";


    //seesion object
    String TEMP_SMS_LIST = "session_temp_sms_list";
    String TEMP_MAIL_LIST = "session_temp_mail_list";
    //Sms Mail Status
    int SMS_MAIL_STATUS_READY = 0;
    int SMS_MAIL_STATUS_SENT = 1;

    //CA Order status
    int CA_ORDER_STATUS_CREATE = 1;
    int CA_ORDER_STATUS_CHECK = 2;
    int CA_ORDER_STATUS_APPROVE = 3;
    int CA_ORDER_STATUS_FI_APPROVE = 4;
    int CA_ORDER_STATUS_PAY = 5;
    // 新增加两个状态 财务审核,财务审批
    int CA_ORDER_STATUS_FINANCIAL_CHECK = 6;
    int CA_ORDER_STATUS_FINANCIAL_APPROVE = 7;


    //Sap order type
    int SAP_TYPE_ORDER = 1;
    int SAP_TYPE_REFUND = 2;
    int SAP_TYPE_SELF_TO_DIS = 2;
    int SAP_TYPE_DIS_TO_SELF = 1;
    int SAP_TYPE_RESKU = 3;
    int SAP_TYPE_REGIFT = 3;

    //order origin
    int ORDER_ORIGION_JINGDONG = 2;
    int ORDER_ORIGION_JINGDONG2 = 11;
    int ORDER_ORIGION_RE_SKU = 7;
    int ORDER_ORIGION_RE_GIFT = 8;
    //order list query type
    String ORDER_LIST_TYPE_ADMIN = "admin";
    String ORDER_LIST_TYPE_CS = "cusServ";
    String ORDER_LIST_TYPE_SELF_WH = "selfWh";
    String ORDER_LIST_TYPE_DIS = "dis";
    String ORDER_LIST_TYPE_FI = "financial";

    /**
     * entity status
     */
    int ENTITY_STATUS_REMOVED = -1;
    int ENTITY_STATUS_USABLE = 1;
    int ENTITY_STATUS_UNUSABLE = 2;

    //Default self warehouse uuid
    String DEFAULT_SELF_WAREHOUSE_ORGID = "UUID_ORG_000000000_0149000000000";

    //Customer Type
    int CUSTOMER_TYPE_MEMBER = 1;
    int CUSTOMER_TYPE_NORMAL = 2;

    //delivery type
    int DELIVERY_TYPE_SELF = 1;
    int DELIVERY_TYPE_DISTRIBUTOR = 2;

    //Role Id
    String ROLE_ID_ADMIN = "ROLEROLEROLEROLEROLEROLEROLE0001";
    String ROLE_ID_CUSSERV = "ROLEROLEROLEROLEROLEROLEROLE0002";
    String ROLE_ID_FINANCE = "ROLEROLEROLEROLEROLEROLEROLE0003";
    String ROLE_ID_SELFWH = "ROLEROLEROLEROLEROLEROLEROLE0004";
    String ROLE_ID_SALES = "ROLEROLEROLEROLEROLEROLEROLE0005";
    String ROLE_ID_DIS = "ROLEROLEROLEROLEROLEROLEROLE0006";

    /*
     * Origin
     */
    int ORIGIN_TIANMAO = 1;
    int ORIGIN_JINGDONG = 2;
    int ORIGIN_NIPPON = 3;
    int ORIGIN_SINA = 4;
    int ORIGIN_TAOBAODIS = 5;
    int ORIGIN_OTHER = 6;
    int ORIGIN_RE_SKU = 7;
    int ORIGIN_RE_GIFT = 8;
    int ORIGIN_AMAZON = 9;
    int ORIGIN_SUNING = 10;
    int ORIGIN_JINGDONG2 = 11;
    int ORIGIN_TIANMAO_ACC = 12;
    int ORIGIN_JINGDONG_SX = 13;
    int ORIGIN_JINGDONG_QS = 14;
    int ORIGIN_JINGDONG_TS = 15;
    int ORIGIN_JINGDONG_CF = 16;


    int ORIGIN_FX_JD_01 = 30;


    int ORIGIN_TIANMAO_PB = 50;
    int ORIGIN_TIANMAO_O2O = 51;
    int ORIGIN_ICOLOR = 88;


    /*
     * Sales order inner status
     */
    int ORDER_INNER_STATUS_CLOSE = -1;
    int ORDER_INNER_STATUS_CANCEL = 0;
    int ORDER_INNER_STATUS_NEW_NEED_PAY = 1;
    int ORDER_INNER_STATUS_NEW_NEED_APPROVE = 2;
    int ORDER_INNER_STATUS_COMMIT_NEED_SEND = 3;
    int ORDER_INNER_STATUS_SENT = 4;
    int ORDER_INNER_STATUS_SUCCESS = 5;
    int ORDER_INNER_STATUS_REFUNDING = 6;
    int ORDER_INNER_STATUS_REFUNDED = 7;

    int ORDER_LINE_LIFE_STATUS_REFUND_UNSEND = 2;
    int ORDER_LINE_LIFE_STATUS_REFUND_SEND = 3;
    int ORDER_LINE_LIFE_STATUS_REFUND_SUCCESS = 4;

    int REFUND_INNER_STATUS_NEW = 1;
    int REFUND_INNER_STATUS_CS_NO = 2;
    int REFUND_INNER_STATUS_CS_OK = 3;
    int REFUND_INNER_STATUS_SENDER_NO = 4;
    int REFUND_INNER_STATUS_SENDER_OK = 5;
    int REFUND_INNER_STATUS_WH_NO = 6;
    int REFUND_INNER_STATUS_WH_OK = 7;
    int REFUND_INNER_STATUS_APPROVED = 8;
    int REFUND_INNER_STATUS_PAY_FAIL = 9;
    int REFUND_INNER_STATUS_PAY_PASS = 10;
    int REFUND_INNER_STATUS_FI_CHECK = 11;
    int REFUND_INNER_STATUS_FI_APPROVE = 12;

    /**
     * entity attrnames
     */
    String DELEGATE_SEPARATOR = ".";
    String INDICATE = "Indicate";
    String FK_PREFIX = "_FK";
    String OBJ_PREFIX = "_OBJ";

    //propertyReader
    String COL_DELIM_IN_PROPERTIES = ",";

    String GET_ENTITY_TYPE_METHOD = "getEntityType";
    String KEY_FOR_PAGE_COUNT = "PageCount";
    String KEY_FOR_QUERY_RESULT = "QueryResult";


    //Form Submit Type
    String FORM_SUBMIT_OPERATION_TYPE = "operationType";
    String FORM_SUBMIT_OPERATION_DELETE = "D";
    String FORM_SUBMIT_OPERATION_REAL_DELETE = "R";
    String FORM_SUBMIT_OPERATION_UPDATE = "M";
    String FORM_SUBMIT_OPERATION_INSERT = "A";


    // *
    // *
    // *
    // *

    String COL_DELIM = "\u001C";
    String ROW_DELIM = "\u001B";
    String TEXT_QUALIFIER = "\u001A";
    String SPEARMARK = "\u0014";
    String COL_DELIM_BAK = "\u001D";
    String PARAGRAPH_DELIM = "\u0015";


    String DATATYPE_STRING = "String";
    String DATATYPE_INGEGER = "Integer";
    String DATATYPE_DOUBLE = "Double";
    String DATATYPE_LONG = "Long";
    //    public static final String DATATYPE_FLOAT ="java.lang.Float";
//    public static final String DATATYPE_NUMBER = "java.lang.Number";
    String DATATYPE_BOOLEAN = "Boolean";
    String DATATYPE_SQL_DATE = "Date";
    //    public static final String DATATYPE_UTIL_DATE = "java.util.Date";
    String DATATYPE_TIME = "Time";
    String DATATYPE_BLOB = "Blob";


    String FORWARD_SUCCESS = "success";
    String FORWARD_ERROR = "error";
    String FORWARD_ORDER_LIST_CUSSERV = "cus_serv";
    String FORWARD_ORDER_LIST_SELF_WH = "self_wh";
    String FORWARD_ORDER_LIST_DISTRIBUTOR = "distributor";


    //public String for model savedata.jsp
    String PAGE_FLAG = "bsuccess";
    String ERROR_MSG = "errormsg";
    String COMMON_CODE = "commoncode";
    String COMMON_RETCODE = "commonretcode";
    String COMMON_UUID = "commonuuid";
    String PAGE_INITFALSE = "initFalse";
    String PAGE_SUCCESS = "yes";
    String PAGE_FAIL = "no";
    String BACK_MSG = "back_msg";
    String BUSINESS_ERROR_MSG = "businesserrormsg";
    String SYSTEM_ERROR_MSG = "systemerrormsg";
    String BUSINESS_ERROR_MSG_TRACE = "businesserrormsgtrace";
    String SYSTEM_ERROR_MSG_TRACE = "systemerrormsgtrace";
    String TABLE_DATA = "tabledatas";

    //public String for model ModelGetMainInfoAction.java
    String MAIN_INFO = "maininfo";
    String DIRECT = "commondirect";

    int PRE_PAGE = 1;

    long TIME_INV = 8 * 3600 * 1000;
    String EMPTY_PREFIX = "_EMPTY";

    //Issue Recorde type
    int ISSUE_TYPE_QULITY = 6;
    int ISSUE_TYPE_LOGI = 11;
    int ISSUE_TYPE_BILL = 1;
    int ISSUE_TYPE_OTHER = 4;
    int ISSUE_TYPE_order = 9;


}

